version: '3.8'
services:
  db:
    image: postgres:14.4-alpine
    restart: always
    environment:
      - POSTGRES_USER=beeper
      - POSTGRES_PASSWORD=localtesting1234
    ports:
      - '5432:5432'
    volumes:
      - ./postgres:/var/lib/postgresql/data