name: beeper
description: A discord bot.
publish_to: none
version: 0.0.1

environment:
  sdk: '>=2.17.5 <3.0.0'

dependencies:
  async: ^2.4.2
  beeper_common:
    path: common
  clock: ^1.0.1
  collection: ^1.16.0
  http: ^0.13.4
  lints: ^2.0.0
  path: ^1.7.0
  pointycastle: ^3.6.1
  postgres: ^2.2.0
  rxdart: ^0.27.5
  shelf_proxy: any
  stack_trace: ^1.9.6
  strings: ^0.2.2
  tuple: ^2.0.0
  watcher: ^1.0.1
  yaml: ^3.1.0

dev_dependencies:
  build_runner: ^2.2.0
  dart_style: ^2.2.3
  fake_async: ^1.1.0
  hotreloader: ^3.0.5
  source_gen: ^1.2.2
  test: ^1.14.4
